apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-edge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-edge
  template:
    metadata:
      labels:
        app: nginx-edge
    spec:
      # This is the magic part! 
      # It forces the app to go to your Edge Node (The Fake Pi)
      nodeSelector:
        node-type: edge
      containers:
      - name: nginx
        image: abdelmouaiz/pfe-web-app:cf14289
        ports:
        - containerPort: 80
