name: Production Build & Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/website/**'
      - '.github/workflows/ci-cd.yaml'

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Define outputs so the next job can read the version tag
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: src/website
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/pfe-web-app:${{ steps.vars.outputs.sha_short }}
            ${{ secrets.DOCKER_USERNAME }}/pfe-web-app:latest

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Update Kubernetes Manifest
        run: |
          git config --global user.name 'GitHub Actions CI'
          git config --global user.email 'actions@github.com'

          # GET THE VERSION FROM THE PREVIOUS JOB
          NEW_TAG=${{ needs.build-and-push.outputs.sha_short }}
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/pfe-web-app
          FILE_PATH=edge-apps/nginx/deployment.yaml
          
          echo "Updating image to: $IMAGE_NAME:$NEW_TAG"

          # EDIT THE FILE
          sed -i "s|image: .*|image: $IMAGE_NAME:$NEW_TAG|g" $FILE_PATH

          # COMMIT AND PUSH
          git add $FILE_PATH
          git commit -m "ðŸš€CI: Updated image to version $NEW_TAG" || echo "No changes to commit"
          git push
